using Godot;
using System;
// Generated by gemini just for a test script using the following prompt:
// "write a godot script that inherits from RigidBody3D that takes inputs and pushes applies a force to the rigidbody3d from those inputs"
// I then instructed it to port to C# from gdscript
public partial class TestHingeMover : RigidBody3D
{
// -- Configuration --
    [ExportGroup("Movement Settings")]
    
    [Export]
    public float MovementForce = 10.0f;
    
    [Export]
    public float MaxSpeed = 10.0f;

    // -- Camera Reference --
    // Assign in Inspector to move relative to camera view
    [Export]
    public Camera3D ViewCamera;

    public override void _Ready()
    {
        // Optional: Ensure gravity scale is standard
        GravityScale = 1.0f;
    }

    public override void _PhysicsProcess(double delta)
    {
        HandleMovementInput();
        LimitSpeed();
    }

    private void HandleMovementInput()
    {
        // 1. Get Input Vector
        // Returns a Vector2 where X is left/right and Y is up/down
        Vector2 inputDir = Input.GetVector("ui_left", "ui_right", "ui_up", "ui_down");

        // Optimization: If no input, return early
        if (inputDir == Vector2.Zero) return;

        Vector3 direction = Vector3.Zero;

        if (ViewCamera != null)
        {
            // Move relative to the camera's rotation
            Basis camBasis = ViewCamera.GlobalTransform.Basis;
            direction = (camBasis.X * inputDir.X) + (camBasis.Z * inputDir.Y);
            
            // Flatten Y so we don't fly upward when looking up
            direction.Y = 0;
            direction = direction.Normalized();
        }
        else
        {
            // Move relative to global world coordinates (Top-down view logic)
            // Note: inputDir.Y corresponds to 3D Z-axis
            direction = new Vector3(inputDir.X, 0, inputDir.Y).Normalized();
        }

        // 2. Apply the force
        ApplyCentralForce(direction * MovementForce);
    }

    private void LimitSpeed()
    {
        // Prevent infinite acceleration
        if (LinearVelocity.Length() > MaxSpeed)
        {
            LinearVelocity = LinearVelocity.Normalized() * MaxSpeed;
        }
    }
}
